# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
# TODO: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#example-configuration
# TODO: https://github.com/softprops/action-gh-release/pull/179

name: build and release

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Release
        uses: softprops/action-gh-release@master
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          generate_release_notes: true
          files: |
            build/libs/*.jar
